"""empty message

Revision ID: 29ee4ab9e063
Revises: 378d9d5025cf
Create Date: 2018-05-15 13:57:49.672243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ee4ab9e063'
down_revision = '378d9d5025cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('random', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'random')
    # ### end Alembic commands ###
