"""empty message

Revision ID: 378d9d5025cf
Revises: a0ba459d4e0e
Create Date: 2018-05-15 11:39:54.934702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '378d9d5025cf'
down_revision = 'a0ba459d4e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('tickets', 'tite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('tite', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tickets', 'title')
    # ### end Alembic commands ###
