"""empty message

Revision ID: a0ba459d4e0e
Revises: 3508c61c60e9
Create Date: 2018-04-17 17:00:33.179225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0ba459d4e0e'
down_revision = '3508c61c60e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('reset_password_token', sa.String(length=255), nullable=True))
    op.drop_column('clients', 'reset_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('reset_password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('clients', 'reset_password_token')
    # ### end Alembic commands ###
